### ISSUE TITLE
提示Cupy出错

### ISSUE THREAD

**Issue by LumenScope** [BICLab/Spike-Driven-Transformer#11]
```
(sllama2) (base) root@9c83119027b1:/home/SLLaMA# /root/miniconda3/envs/sllama2/bin/python /home/SLLaMA/Spike-Driven-Transformer_原版/model/spikeformer.py
Traceback (most recent call last):
  File "/home/SLLaMA/Spike-Driven-Transformer_原版/model/spikeformer.py", line 153, in <module>
    model = SpikeDrivenTransformer()
  File "/home/SLLaMA/Spike-Driven-Transformer_原版/model/spikeformer.py", line 60, in __init__
    patch_embed = MS_SPS(
  File "/home/SLLaMA/Spike-Driven-Transformer_原版/model/sps.py", line 38, in __init__
    self.proj_lif = MultiStepLIFNode(tau=2.0, detach_reset=True, backend="cupy")
  File "/root/miniconda3/envs/sllama2/lib/python3.8/site-packages/spikingjelly/clock_driven/neuron.py", line 823, in __init__
    check_backend(backend)
  File "/root/miniconda3/envs/sllama2/lib/python3.8/site-packages/spikingjelly/clock_driven/neuron.py", line 30, in check_backend
    assert cupy is not None, 'CuPy is not installed! You can install it from "https://github.com/cupy/cupy".'
AssertionError: CuPy is not installed! You can install it from "https://github.com/cupy/cupy".
(sllama2) (base) root@9c83119027b1:/home/SLLaMA# /root/miniconda3/envs/sllama2/bin/python /home/SLLaMA/SLLaMA-7B/test.py
10.6.0
```
当我想打印模型：
```
# 创建模型实例
model = SpikeDrivenTransformer()

# 打印模型
print(model)
```

**Comment by jkhu29** [comment]
此issue与spikingkjelly相关，请前往spikingjelly提issue。另：当`spikingjelly==0.0.0.0.12`请先下载tensorboard。具体原因我在spikingjelly相关issue中有解释。
