### ISSUE TITLE
cupy problem!

### ISSUE THREAD

**Issue by codeinging** [BICLab/Spike-Driven-Transformer#4]
I have installed cupy in conda:
<img width="1002" alt="image" src="https://github.com/BICLab/Spike-Driven-Transformer/assets/14802882/f6affdd7-9dfe-4103-b45b-1aaf1df05407">
But still encounter a problem：
Traceback (most recent call last):
  File "train.py", line 1679, in <module>
    main()
  File "train.py", line 976, in main
    TET=args.TET,
  File "/home/visitor/anaconda3/envs/spike_transformer_syd/lib/python3.7/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/data1/experiment_code/sunyundong/PyGT/Spike-Driven-Transformer/model/spikeformer.py", line 144, in sdt
    **kwargs,
  File "/data1/experiment_code/sunyundong/PyGT/Spike-Driven-Transformer/model/spikeformer.py", line 64, in __init__
    spike_mode=spike_mode,
  File "/data1/experiment_code/sunyundong/PyGT/Spike-Driven-Transformer/module/sps.py", line 38, in __init__
    self.proj_lif = MultiStepLIFNode(tau=2.0, detach_reset=True, backend="cupy")
  File "/home/visitor/anaconda3/envs/spike_transformer_syd/lib/python3.7/site-packages/spikingjelly/clock_driven/neuron.py", line 823, in __init__
    check_backend(backend)
  File "/home/visitor/anaconda3/envs/spike_transformer_syd/lib/python3.7/site-packages/spikingjelly/clock_driven/neuron.py", line 30, in check_backend
    assert cupy is not None, 'CuPy is not installed! You can install it from "https://github.com/cupy/cupy".'
AssertionError: CuPy is not installed! You can install it from "https://github.com/cupy/cupy".

**Comment by jkhu29** [comment]
Thanks for your interest in this project. This issue looks more relevant to [spikingjelly](https://github.com/fangwei123456/spikingjelly), please submit your issue [here](https://github.com/fangwei123456/spikingjelly/issues).

Related issues:
https://github.com/zhouchenlin2096/Spikingformer/issues/1
https://github.com/fangwei123456/spikingjelly/issues/408
